services:
  api:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8080"
    hostname: api01
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_SECRET=${DB_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "340MB"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: django-base-setup
