name: Portifolio API

on:
  push:
    branches:
      - develop



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_SECRET: ${{ secrets.DB_SECRET }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DEBUG: ${{ secrets.DEBUG }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DEVELOPMENT_MODE: ${{ secrets.DEVELOPMENT_MODE }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Taskipy
        run: |
          python -m pip install --upgrade pip
          pip install taskipy

      - name: Verify Environment Variables
        run: |
          echo "SECRET_KEY=$SECRET_KEY"
          echo "DATABASE_URL=$DATABASE_URL"
          echo "DB_USERNAME=$DB_USERNAME"
          echo "DB_SECRET=$DB_SECRET"
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_NAME=$DB_NAME"
          echo "DEBUG=$DEBUG"
          echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS"
          echo "DEVELOPMENT_MODE=$DEVELOPMENT_MODE"
          echo "POSTGRES_DB=$POSTGRES_DB"
          echo "POSTGRES_USER=$POSTGRES_USER"
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"

      - name: Running tests with Docker
        run: task tests
